version: '3'

services:
  blize-php8:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: "blize-php8"
    networks:
      - blize-network
    volumes:
      - .:/var/www/html
    depends_on:
      - blize-php8_mysql

  blize-php8_nginx:
    image: nginx:latest
    container_name: "blize-php8_nginx"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    networks:
      - blize-network
    ports:
      - "8082:8082"
    depends_on:
      - blize-php8

  blize-php8_redis:
    image: redis:latest
    container_name: "blize-php8_redis"
    ports:
      - "6379:6379"
    networks:
      - blize-network

  blize-php8_mongo:
    image: mongo:latest
    container_name: "blize-php8_mongo"
    ports:
      - "27017:27017"
    networks:
      - blize-network

  blize-php8_mysql:
    image: mysql:latest
    container_name: "blize-php8_mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blize
      - MYSQL_USER=blize
      - MYSQL_PASSWORD=blize
    networks:
      - blize-network

networks:
  blize-network:
    external: true
